name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Get PR Diff
        id: get_diff
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > diff.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send diff to OpenWebUI
        id: ai_review
        run: |
          DIFF=$(jq -Rs . < diff.txt)

          RESPONSE=$(curl -s -X POST "$OPENWEBUI_API_URL" \
            -H "Authorization: Bearer $OPENWEBUI_TOKEN" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
{
  "model": "qwen2.5-coder:7b",
  "messages": [
    {
      "role": "system",
      "content": "You are an expert code reviewer. Analyze the following diff and suggest improvements:"
    },
    {
      "role": "user",
      "content": $DIFF
    }
  ]
}
EOF
          )

          echo "$RESPONSE" > review.md
        env:
          OPENWEBUI_API_URL: ${{ secrets.OPENWEBUI_API_URL }}
          OPENWEBUI_TOKEN: ${{ secrets.OPENWEBUI_TOKEN }}

      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -F review.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
